#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = iar.targets.arm.M3{1,0,7.40,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/heartBeat_prm3.orm3.dep
package/cfg/heartBeat_prm3.orm3.dep: ;
endif

package/cfg/heartBeat_prm3.orm3: | .interfaces
package/cfg/heartBeat_prm3.orm3: package/cfg/heartBeat_prm3.c package/cfg/heartBeat_prm3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clrm3 $< ...
	LC_ALL=C $(iar.targets.arm.M3.rootDir)/bin/iccarm    -D TI_DRIVERS_I2C_INCLUDED   -Ic:/ti/tirtos_cc13xx_cc26xx_2_16_01_14/products/cc13xxware_2_03_02_16941   -Dewarm   -IC:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/smartrf_settings   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/common/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/UART/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/OLED/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/I2C/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/userApp/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/RF/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/swTool/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/ADC/   --silent --aeabi --cpu=Cortex-M3 --diag_suppress=Pa050,Go005 --endian=little -e --thumb   -Dxdc_cfg__xheader__='"configPkg/package/cfg/heartBeat_prm3.h"'  -Dxdc_target_name__=M3 -Dxdc_target_types__=iar/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_7_40_3 -Ohs --dlib_config $(iar.targets.arm.M3.rootDir)/inc/c/DLib_Config_Normal.h  $(XDCINCS)  -o $@  $<
	
	-@$(FIXDEP) $@.dep $@.dep
	

package/cfg/heartBeat_prm3.srm3: | .interfaces
package/cfg/heartBeat_prm3.srm3: package/cfg/heartBeat_prm3.c package/cfg/heartBeat_prm3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clrm3 $< ...
	LC_ALL=C $(iar.targets.arm.M3.rootDir)/bin/iccarm    -D TI_DRIVERS_I2C_INCLUDED   -Ic:/ti/tirtos_cc13xx_cc26xx_2_16_01_14/products/cc13xxware_2_03_02_16941   -Dewarm   -IC:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/smartrf_settings   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/common/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/UART/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/OLED/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/I2C/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/userApp/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/RF/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/swTool/   -I C:/work/source/ALL_HeartRate_CC1310/software/IAR/worksplace/HeartRate/Application/Drivers/ADC/   --silent --aeabi --cpu=Cortex-M3 --diag_suppress=Pa050,Go005 --endian=little -e --thumb   -Dxdc_cfg__xheader__='"configPkg/package/cfg/heartBeat_prm3.h"'  -Dxdc_target_name__=M3 -Dxdc_target_types__=iar/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_7_40_3 -Ohs --dlib_config $(iar.targets.arm.M3.rootDir)/inc/c/DLib_Config_Normal.h  $(XDCINCS)  -o $@  $<
	
	-@$(FIXDEP) $@.dep $@.dep
	

clean,rm3 ::
	-$(RM) package/cfg/heartBeat_prm3.orm3
	-$(RM) package/cfg/heartBeat_prm3.srm3

heartBeat.prm3: package/cfg/heartBeat_prm3.orm3 package/cfg/heartBeat_prm3.mak

clean::
	-$(RM) package/cfg/heartBeat_prm3.mak
